# Generated by Django 4.1 on 2022-09-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0003_repo_last_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="repokey",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="repokey",
            name="balance",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="repokey",
            name="is_private_key",
            field=models.BooleanField(default=False),
        ),
    ]
