# Generated by Django 4.1 on 2022-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0004_repokey_address_repokey_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repokey",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
